# Generated by Django 5.1.5 on 2025-01-21 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0002_referee_customer_referee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='identity_document',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='income_proof',
        ),
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='customers/photos/'),
        ),
        migrations.AddField(
            model_name='referee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='referees/photos/'),
        ),
        migrations.AlterField(
            model_name='loanofficer',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='loan_officer_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='loanofficer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='loan_officer_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='relationship_to_customer',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='repayments/receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='dashboard.loanapplication')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
