# Generated by Django 5.1.5 on 2025-01-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_loanapplication_identity_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanofficer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='loan_officers/photos/'),
        ),
    ]
