# Generated by Django 5.1.5 on 2025-01-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_loanofficer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanofficer',
            name='username',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='loanofficer',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
