# Generated by Django 5.1.5 on 2025-01-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_address_remove_customer_referee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
