# Generated by Django 5.1.5 on 2025-01-27 19:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_loanapplication_approved_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanofficer',
            options={'verbose_name': 'Loan Officer', 'verbose_name_plural': 'Loan Officers'},
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_type', models.CharField(choices=[('personal', 'Personal'), ('institution', 'Institution')], default='personal', max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.loanofficer')),
            ],
            options={
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
