# Generated by Django 5.1.5 on 2025-01-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_loanofficer_options_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanofficer',
            name='username',
        ),
        migrations.AlterField(
            model_name='loanofficer',
            name='employee_id',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
