# Generated by Django 5.1.5 on 2025-01-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_loanofficer_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanofficer',
            name='employee_id',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
    ]
