# Generated by Django 5.1.5 on 2025-02-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_loanofficer_employee_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AddField(
            model_name='customer',
            name='id_type',
            field=models.CharField(choices=[('NIDA', 'National ID'), ('VOTER', 'Voter ID'), ('OTHER', 'Other')], default='NIDA', max_length=10),
        ),
    ]
