# Generated by Django 5.1.5 on 2025-02-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_customer_options_customer_id_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='photo',
        ),
        migrations.AddField(
            model_name='customer',
            name='id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='customers/id_photos/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='customers/profile_pictures/'),
        ),
    ]
