# Generated by Django 5.1.5 on 2025-02-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_customer_photo_customer_id_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='collateral_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='collateral_photo',
            field=models.ImageField(blank=True, null=True, upload_to='collaterals/photos/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='collateral_type',
            field=models.CharField(choices=[('vehicle', 'Vehicle'), ('land', 'Land'), ('house', 'House'), ('equipment', 'Equipment'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
