# Generated by Django 5.1.5 on 2025-02-07 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_loanapplication_interest_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapplication',
            old_name='agreed_repayment_amount',
            new_name='interest',
        ),
    ]
