# Generated by Django 5.1.4 on 2024-12-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfi_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='microfinance',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
    ]
